# shellcheck shell=bash

# GitHub Actions, Pages, cache, and container orchestration.

cached_builder_image(){
  local package_type="$1"
  local base_image="$2"
  local build_cmd="$3"
  local work cfile digest hash repo image

  work="$ROOT/.builder-image/$package_type"
  cfile="$work/Containerfile"
  mkdir -p "$work"

  digest="$(docker buildx imagetools inspect "$base_image" --format '{{json .Manifest.Digest}}' | tr -d '"')"

  cat >"$cfile" <<EOF
FROM $base_image

RUN $build_cmd
EOF

  hash="$(
    {
      printf 'package_type=%s\n' "$package_type"
      printf 'base_digest=%s\n' "$digest"
      printf 'build_cmd=%s\n' "$build_cmd"
    } | sha256_lines
  )"

  repo="${BUILDER_IMAGE_REPO:-ghcr.io/${GITHUB_REPOSITORY:?}/builder}"
  image="$repo:$package_type-${hash:0:16}"

  if docker buildx imagetools inspect "$image" >/dev/null 2>&1; then
    printf '%s' "$image"
    return 0
  fi

  docker buildx build \
    --file "$cfile" \
    --tag "$image" \
    --push \
    "$ROOT"

  printf '%s' "$image"
}

build_inside_container(){
  local app dir file i title url

  load_apps_sources "${APP:-}" "${SOURCE_GIT:-}"
  ensure_dir /work/public

  rm -rf "$METADATA_DIR"
  ensure_dir "$METADATA_DIR"
  : >"$METADATA_DIR/packages.txt"
  : >"$METADATA_DIR/repos.tsv"
  : >"$METADATA_DIR/targets.txt"

  setup_gpg

  ensure_dir "$PUBLIC_DIR"
  cp /work/gpg-key/public.asc "$PUBLIC_DIR/GPG-KEY-repo"
  case "$PACKAGE_TYPE" in
    rpm)
      rpm --import /work/public/GPG-KEY-repo
      rpm_configure_signing
      ;;
    deb)
      ;;
    *)
      die "Unsupported package-type for repository build: $PACKAGE_TYPE"
      ;;
  esac

  load_apps_sources "${APP:-}" "${SOURCE_GIT:-}"

  for i in "${!APPS[@]}"; do
    app="${APPS[$i]}"
    url="$(source_for_index "$i")"
    dir="$(prepare_app_workdir "$app" "$url" /work/work)"

    SOURCE_ID="$app" PATCH_ROOT="$dir/patches" run_user_build_script "$dir" "${BUILD_SCRIPT:-}"
  done

  case "$PACKAGE_TYPE" in
    rpm)
      rpm_build_targets
      ;;
    deb)
      deb_build_targets
      ;;
    *)
      die "Unsupported package-type for repository build: $PACKAGE_TYPE"
      ;;
  esac

  for file in packages.txt repos.tsv targets.txt; do
    sort_unique_file "$METADATA_DIR/$file"
  done

  title="$(printf '%s Packages' "${PRIMARY_APP:-Repository}" | sed 's/&/\&amp;/g')"
  cat >"$PUBLIC_DIR/index.html" <<EOF
<!doctype html><meta charset="utf-8"><title>$title</title><h1>$title</h1><p>Repository index generated by package builder.</p>
EOF

  require_file "$PUBLIC_DIR/GPG-KEY-repo"
  require_file "$METADATA_DIR/packages.txt"
  require_file "$METADATA_DIR/repos.tsv"
  require_file "$METADATA_DIR/targets.txt"

  case "$PACKAGE_TYPE" in
    rpm)
      compgen -G "$PUBLIC_DIR/*.repo" >/dev/null || die "No RPM .repo file was generated."
      find "$PUBLIC_DIR" -path '*/repodata/repomd.xml' | grep -q . || die "No RPM repodata/repomd.xml was generated."
      ;;
    deb)
      compgen -G "$PUBLIC_DIR/*.sources" >/dev/null || die "No DEB .sources file was generated."
      find "$PUBLIC_DIR" -name Release | grep -q . || die "No DEB Release file was generated."
      find "$PUBLIC_DIR" -name InRelease | grep -q . || die "No DEB InRelease file was generated."
      ;;
  esac
}

cmd_build_container(){
  if [[ "${1:-}" == --inside-container ]]; then
    build_inside_container
    return
  fi

  local package_type="${PACKAGE_TYPE:?}"
  local target family arch
  local base_image=""
  local build_cmd=""
  local first_target=""
  local target_image target_build_cmd
  local image cache_key cache_root
  local env_args=(-e PUBLIC_ROOT=/work/public -e PACKAGE_BUILD_QUEUE_DIR=/work/package-build-queue)
  local cache_args=()
  local var value spec name path

  validate_targets "$package_type"

  while IFS= read -r target; do
    [[ -n "$target" ]] || continue
    IFS=$'\t' read -r family arch < <(split_target "$target")

    target_image="$(target_container_image "$package_type" "$family" "$arch")"
    target_build_cmd="${TARGET_CONTAINER_BUILD_CMD:-}"
    [[ -n "$target_build_cmd" ]] || die "Missing TARGET_CONTAINER_BUILD_CMD for $package_type target: $target"

    if [[ -z "$first_target" ]]; then
      first_target="$target"
      base_image="$target_image"
      build_cmd="$target_build_cmd"
      continue
    fi

    [[ "$target_image" == "$base_image" ]] ||
      die "Targets use different TARGET_CONTAINER_IMAGE values: $first_target uses '$base_image', but $target uses '$target_image'"

    [[ "$target_build_cmd" == "$build_cmd" ]] ||
      die "Targets use different TARGET_CONTAINER_BUILD_CMD values: $first_target and $target differ"
  done < <(targets_list)

  [[ -n "$first_target" ]] || die "$package_type requires targets."

  image="$(cached_builder_image "$package_type" "$base_image" "$build_cmd")"

  cache_key="$(
    {
      printf 'cache_schema=%s\n' "$PACKAGE_CACHE_SCHEMA"
      printf 'package_type=%s\n' "$package_type"

      while IFS= read -r target; do
        [[ -n "$target" ]] || continue
        IFS=$'\t' read -r family arch < <(split_target "$target")
        config_file="$(find_target_config "$package_type" "$family" "$arch")"

        printf 'target=%s\n' "$target"
        printf 'config=%s\n' "${config_file#$ROOT/}"
        printf 'sha256=%s\n' "$(sha256_file "$config_file")"
      done < <(targets_list)
    } | sha256_lines
  )"
  cache_key="$package_type-v$PACKAGE_CACHE_SCHEMA-${cache_key:0:16}"
  cache_root="package-cache/$cache_key"
  mkdir -p "$cache_root"
  {
    printf 'cache_schema=%s\n' "$PACKAGE_CACHE_SCHEMA"
    printf 'package_type=%s\n' "$package_type"
    printf 'created_at=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"

    while IFS= read -r target; do
      [[ -n "$target" ]] || continue
      IFS=$'\t' read -r family arch < <(split_target "$target")
      config_file="$(find_target_config "$package_type" "$family" "$arch")"

      printf 'target=%s\n' "$target"
      printf 'config=%s\n' "${config_file#$ROOT/}"
      printf 'sha256=%s\n' "$(sha256_file "$config_file")"
    done < <(targets_list)
  } >"$cache_root/.repository-builder-cache-manifest"
  echo "Using package cache: $cache_root"

  for var in "${HOST_ENV_VARS[@]}"; do
    [[ -n "${!var+x}" ]] || continue

    value="${!var}"
    if [[ " $TRIMMED_ENV_VARS " == *" $var "* ]]; then
      value="$(sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' <<<"$value")"
    fi

    env_args+=(-e "$var=$value")
  done

  for spec in "${CACHE_MOUNTS[@]}"; do
    name="${spec%%:*}"
    path="${spec#*:}"
    mkdir -p "$cache_root/$name"
    cache_args+=(-v "$PWD/$cache_root/$name:$path")
  done

  docker run \
    --rm \
    --privileged \
    -v "$PWD:/work/workspace" \
    -v "$PWD/publisher:/work/publisher" \
    -v "$PWD/public:/work/public" \
    -v "$PWD/gpg-key:/work/gpg-key" \
    -v "$PWD/$cache_root:/package-cache" \
    "${cache_args[@]}" \
    -w /work/workspace \
    "${env_args[@]}" \
    "$image" \
    bash /work/publisher/repository_builder.sh build-container --inside-container
}

cmd_prepare(){
  local package_type="${PACKAGE_TYPE:-}"
  local family arch container key changed line kind name value ref result sha pages cache_keys file
  local version=()
  local targets=()

  [[ " $PACKAGE_TYPES " == *" $package_type "* ]] || die "Unsupported package-type: $package_type"

  pages="$(gh api "repos/${GITHUB_REPOSITORY:?}/pages" --jq .build_type)"
  [[ "$pages" == workflow ]] || die "Enable GitHub Pages with Source set to GitHub Actions."

  load_apps_sources "${APP:-}" "${SOURCE_GIT:-}"
  [[ -n "${SOURCE_GIT:-}" || -n "${BUILD_SCRIPT:-}" ]] || die "$package_type requires source-git, build-script, or both."

  if [[ "$package_type" == flatpak ]]; then
    mapfile -t targets < <(targets_list)
    ((${#targets[@]} == 1)) || die "Flatpak requires exactly one target."

    validate_target flatpak "${targets[0]}"
    IFS=$'\t' read -r family arch < <(split_target "${targets[0]}")
    container="$(target_container_image flatpak "$family" "$arch")"

    write_output build-container-json "{\"image\":\"$container\",\"options\":\"--privileged\"}"
    write_output flatpak-arch "$arch"
  else
    validate_targets "$package_type"
    write_output build-container-json null
    write_output flatpak-arch x86_64
  fi

  if [[ "${GPG_CACHE_HIT:-}" != true ]]; then
    gpg_generate
  else
    for file in gpg-key/private.asc gpg-key/public.asc gpg-key/fingerprint.txt; do
      [[ -f "$file" ]] || die "Missing cached GPG file: $file"
    done
  fi

  while IFS= read -r line; do
    set -- $line
    kind="${1:-}"
    name="${2:-}"
    value="${3:-}"
    ref="${4:-}"

    case "$kind" in
      "")
        continue
        ;;
      url)
        result="$(curl -fsSL --retry 3 --retry-delay 10 --retry-all-errors "$value")"
        version+=("$name	url	$value	$result")
        ;;
      git)
        ref="${ref:-HEAD}"
        sha="$(git ls-remote "$value" "$ref" | awk 'NR==1{print $1}')"
        [[ -n "$sha" ]] || die "Unable to resolve git trigger: $value $ref"
        version+=("git $name $value $ref $sha")
        ;;
      file)
        [[ -f "$value" ]] || die "Missing trigger file: $value"
        version+=("file $name $value $(sha256_file "$value")")
        ;;
      *)
        die "Unknown rebuild-trigger type: $kind"
        ;;
    esac
  done < <(printf '%s\n' "${REBUILD_TRIGGER:-}" | sed -e 's/[[:space:]]*$//' -e '/^[[:space:]]*#/d' -e '/^[[:space:]]*$/d')

  printf '%b\n' "${version[@]:-}" >version.txt
  key="upstream-state-$(printf '%s' "${APP:-}" | sha256sum | awk '{print $1}')-$(sha256_file version.txt)"

  write_output version-key "$key"
  write_output gpg-cache-key package-gpg-key-v1

  if [[ "${GITHUB_EVENT_NAME:-}" == workflow_dispatch ]]; then
    changed=true
  else
    cache_keys="$(gh cache list --key "$key" --json key --jq '.[].key')"
    if grep -qxF "$key" <<<"$cache_keys"; then
      changed=false
    else
      changed=true
    fi
  fi

  write_output changed "$changed"
}

