# shellcheck shell=bash

# GitHub Actions, Pages, cache, and container orchestration.

validate_cache_mode(){
  case "${CACHE_MODE:-normal}" in
    normal|debug|off)
      ;;
    *)
      die "Unsupported cache-mode: ${CACHE_MODE}. Expected normal, debug, or off."
      ;;
  esac
}

cached_builder_image(){
  local package_type="$1"
  local base_image="$2"
  local build_cmd="$3"
  local work cfile digest hash repo image

  work="$ROOT/.builder-image/$package_type"
  cfile="$work/Containerfile"
  mkdir -p "$work"

  digest="$(docker buildx imagetools inspect "$base_image" --format '{{json .Manifest.Digest}}' | tr -d '"')"

  cat >"$cfile" <<EOF
FROM $base_image

RUN $build_cmd
EOF

  hash="$(
    {
      printf 'package_type=%s\n' "$package_type"
      printf 'base_digest=%s\n' "$digest"
      printf 'build_cmd=%s\n' "$build_cmd"
    } | sha256_lines
  )"

  repo="${BUILDER_IMAGE_REPO:-ghcr.io/${GITHUB_REPOSITORY:?}/builder}"
  image="$repo:$package_type-${hash:0:16}"

  if docker buildx imagetools inspect "$image" >/dev/null 2>&1; then
    printf '%s' "$image"
    return 0
  fi

  docker buildx build \
    --file "$cfile" \
    --tag "$image" \
    --push \
    "$ROOT"

  printf '%s' "$image"
}

build_inside_container(){
  local app dir file i title url

  load_apps_sources "${APP:-}" "${SOURCE_GIT:-}"
  ensure_dir /work/public

  if [[ "${BUILDER_GROUP_INDEX:-0}" == 0 ]]; then
    rm -rf "$METADATA_DIR"
    ensure_dir "$METADATA_DIR"
    : >"$METADATA_DIR/packages.txt"
    : >"$METADATA_DIR/repos.tsv"
    : >"$METADATA_DIR/targets.txt"
  else
    ensure_dir "$METADATA_DIR"
    touch "$METADATA_DIR/packages.txt" "$METADATA_DIR/repos.tsv" "$METADATA_DIR/targets.txt"
  fi

  setup_gpg

  ensure_dir "$PUBLIC_DIR"
  cp /work/gpg-key/public.asc "$PUBLIC_DIR/GPG-KEY-repo"
  case "$PACKAGE_TYPE" in
    rpm)
      rpm --import /work/public/GPG-KEY-repo
      rpm_configure_signing
      ;;
    deb)
      ;;
    *)
      die "Unsupported package-type for repository build: $PACKAGE_TYPE"
      ;;
  esac

  load_apps_sources "${APP:-}" "${SOURCE_GIT:-}"

  for i in "${!APPS[@]}"; do
    app="${APPS[$i]}"
    url="$(source_for_index "$i")"
    dir="$(prepare_app_workdir "$app" "$url" /work/work)"

    SOURCE_ID="$app" PATCH_ROOT="$dir/patches" run_user_build_script "$dir" "${BUILD_SCRIPT:-}"
  done

  case "$PACKAGE_TYPE" in
    rpm)
      rpm_build_targets
      ;;
    deb)
      deb_build_targets
      ;;
    *)
      die "Unsupported package-type for repository build: $PACKAGE_TYPE"
      ;;
  esac

  for file in packages.txt repos.tsv targets.txt; do
    sort_unique_file "$METADATA_DIR/$file"
  done

  title="$(printf '%s Packages' "${PRIMARY_APP:-Repository}" | sed 's/&/\&amp;/g')"
  cat >"$PUBLIC_DIR/index.html" <<EOF
<!doctype html><meta charset="utf-8"><title>$title</title><h1>$title</h1><p>Repository index generated by package builder.</p>
EOF

  require_file "$PUBLIC_DIR/GPG-KEY-repo"
  require_file "$METADATA_DIR/packages.txt"
  require_file "$METADATA_DIR/repos.tsv"
  require_file "$METADATA_DIR/targets.txt"

  case "$PACKAGE_TYPE" in
    rpm)
      compgen -G "$PUBLIC_DIR/*.repo" >/dev/null || die "No RPM .repo file was generated."
      find "$PUBLIC_DIR" -path '*/repodata/repomd.xml' | grep -q . || die "No RPM repodata/repomd.xml was generated."
      ;;
    deb)
      compgen -G "$PUBLIC_DIR/*.sources" >/dev/null || die "No DEB .sources file was generated."
      find "$PUBLIC_DIR" -name Release | grep -q . || die "No DEB Release file was generated."
      find "$PUBLIC_DIR" -name InRelease | grep -q . || die "No DEB InRelease file was generated."
      ;;
  esac
}

cmd_build_container(){
  if [[ "${1:-}" == --inside-container ]]; then
    build_inside_container
    return
  fi

  local package_type="${PACKAGE_TYPE:?}"
  local target family arch target_image target_build_cmd group_id group_dir group_count group_index group_targets group_image group_build_cmd image
  local cache_root var value spec name path
  local env_args_common=(-e PUBLIC_ROOT=/work/public -e PACKAGE_BUILD_QUEUE_DIR=/work/package-build-queue)
  local cache_args=()
  local groups=()
  local config_file

  validate_cache_mode
  validate_targets "$package_type"

  group_dir="$ROOT/.builder-groups/$package_type"
  rm -rf "$group_dir"
  mkdir -p "$group_dir"

  while IFS= read -r target; do
    [[ -n "$target" ]] || continue
    IFS=$'\t' read -r family arch < <(split_target "$target")

    target_image="$(target_container_image "$package_type" "$family" "$arch")"
    target_build_cmd="${TARGET_CONTAINER_BUILD_CMD:-}"
    [[ -n "$target_build_cmd" ]] || die "Missing TARGET_CONTAINER_BUILD_CMD for $package_type target: $target"

    group_id="$(
      {
        printf 'package_type=%s\n' "$package_type"
        printf 'image=%s\n' "$target_image"
        printf 'build_cmd=%s\n' "$target_build_cmd"
      } | sha256_lines
    )"
    group_id="${group_id:0:16}"

    if [[ ! -f "$group_dir/$group_id.targets" ]]; then
      groups+=("$group_id")
      printf '%s' "$target_image" >"$group_dir/$group_id.image"
      printf '%s' "$target_build_cmd" >"$group_dir/$group_id.build-cmd"
      : >"$group_dir/$group_id.targets"
    fi

    printf '%s\n' "$target" >>"$group_dir/$group_id.targets"
  done < <(targets_list)

  ((${#groups[@]})) || die "$package_type requires targets."

  cache_root="package-cache/$package_type-v$PACKAGE_CACHE_SCHEMA"
  mkdir -p "$cache_root"
  {
    printf 'cache_schema=%s\n' "$PACKAGE_CACHE_SCHEMA"
    printf 'package_type=%s\n' "$package_type"
    printf 'cache_mode=%s\n' "${CACHE_MODE:-normal}"
    printf 'created_at=%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf 'builder_groups=%s\n' "${#groups[@]}"

    group_index=0
    for group_id in "${groups[@]}"; do
      group_image="$(cat "$group_dir/$group_id.image")"
      group_build_cmd="$(cat "$group_dir/$group_id.build-cmd")"
      printf '\n[group %s]\n' "$group_index"
      printf 'id=%s\n' "$group_id"
      printf 'image=%s\n' "$group_image"
      printf 'build_cmd_sha256=%s\n' "$(printf '%s' "$group_build_cmd" | sha256_lines)"

      while IFS= read -r target; do
        [[ -n "$target" ]] || continue
        IFS=$'\t' read -r family arch < <(split_target "$target")
        config_file="$(find_target_config "$package_type" "$family" "$arch")"
        printf 'target=%s\n' "$target"
        printf 'config=%s\n' "${config_file#$ROOT/}"
        printf 'config_sha256=%s\n' "$(sha256_file "$config_file")"
      done <"$group_dir/$group_id.targets"
      group_index=$((group_index + 1))
    done
  } >"$cache_root/.repository-builder-cache-manifest"
  echo "Using package cache: $cache_root"

  for var in "${HOST_ENV_VARS[@]}"; do
    [[ "$var" != TARGETS ]] || continue
    [[ -n "${!var+x}" ]] || continue

    value="${!var}"
    if [[ " $TRIMMED_ENV_VARS " == *" $var "* ]]; then
      value="$(sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' <<<"$value")"
    fi

    env_args_common+=(-e "$var=$value")
  done

  for spec in "${CACHE_MOUNTS[@]}"; do
    name="${spec%%:*}"
    path="${spec#*:}"
    mkdir -p "$cache_root/$name"
    cache_args+=(-v "$PWD/$cache_root/$name:$path")
  done

  group_count="${#groups[@]}"
  group_index=0
  for group_id in "${groups[@]}"; do
    group_image="$(cat "$group_dir/$group_id.image")"
    group_build_cmd="$(cat "$group_dir/$group_id.build-cmd")"
    group_targets="$(cat "$group_dir/$group_id.targets")"
    image="$(cached_builder_image "$package_type" "$group_image" "$group_build_cmd")"

    echo "==> Builder group $((group_index + 1))/$group_count: image=$group_image targets=$(tr '\n' ' ' <"$group_dir/$group_id.targets" | sed 's/[[:space:]]*$//')"

    docker run \
      --rm \
      --privileged \
      -v "$PWD:/work/workspace" \
      -v "$PWD/publisher:/work/publisher" \
      -v "$PWD/public:/work/public" \
      -v "$PWD/gpg-key:/work/gpg-key" \
      -v "$PWD/$cache_root:/package-cache" \
      "${cache_args[@]}" \
      -w /work/workspace \
      "${env_args_common[@]}" \
      -e "TARGETS=$group_targets" \
      -e "BUILDER_GROUP_INDEX=$group_index" \
      -e "BUILDER_GROUP_COUNT=$group_count" \
      "$image" \
      bash /work/publisher/repository_builder.sh build-container --inside-container

    group_index=$((group_index + 1))
  done
}

cmd_prepare(){
  local package_type="${PACKAGE_TYPE:-}"
  local family arch container key changed line kind name value ref result sha pages cache_keys file
  local version=()
  local targets=()

  [[ " $PACKAGE_TYPES " == *" $package_type "* ]] || die "Unsupported package-type: $package_type"
  validate_cache_mode

  pages="$(gh api "repos/${GITHUB_REPOSITORY:?}/pages" --jq .build_type)"
  [[ "$pages" == workflow ]] || die "Enable GitHub Pages with Source set to GitHub Actions."

  load_apps_sources "${APP:-}" "${SOURCE_GIT:-}"
  [[ -n "${SOURCE_GIT:-}" || -n "${BUILD_SCRIPT:-}" ]] || die "$package_type requires source-git, build-script, or both."

  if [[ "$package_type" == flatpak ]]; then
    mapfile -t targets < <(targets_list)
    ((${#targets[@]} == 1)) || die "Flatpak requires exactly one target."

    validate_target flatpak "${targets[0]}"
    IFS=$'\t' read -r family arch < <(split_target "${targets[0]}")
    container="$(target_container_image flatpak "$family" "$arch")"

    write_output build-container-json "{\"image\":\"$container\",\"options\":\"--privileged\"}"
    write_output flatpak-arch "$arch"
  else
    validate_targets "$package_type"
    write_output build-container-json null
    write_output flatpak-arch x86_64
  fi

  if [[ "${GPG_CACHE_HIT:-}" != true ]]; then
    gpg_generate
  else
    for file in gpg-key/private.asc gpg-key/public.asc gpg-key/fingerprint.txt; do
      [[ -f "$file" ]] || die "Missing cached GPG file: $file"
    done
  fi

  while IFS= read -r line; do
    set -- $line
    kind="${1:-}"
    name="${2:-}"
    value="${3:-}"
    ref="${4:-}"

    case "$kind" in
      "")
        continue
        ;;
      url)
        result="$(curl -fsSL --retry 3 --retry-delay 10 --retry-all-errors "$value")"
        version+=("$name	url	$value	$result")
        ;;
      git)
        ref="${ref:-HEAD}"
        sha="$(git ls-remote "$value" "$ref" | awk 'NR==1{print $1}')"
        [[ -n "$sha" ]] || die "Unable to resolve git trigger: $value $ref"
        version+=("git $name $value $ref $sha")
        ;;
      file)
        [[ -f "$value" ]] || die "Missing trigger file: $value"
        version+=("file $name $value $(sha256_file "$value")")
        ;;
      *)
        die "Unknown rebuild-trigger type: $kind"
        ;;
    esac
  done < <(printf '%s\n' "${REBUILD_TRIGGER:-}" | sed -e 's/[[:space:]]*$//' -e '/^[[:space:]]*#/d' -e '/^[[:space:]]*$/d')

  printf '%b\n' "${version[@]:-}" >version.txt
  key="upstream-state-$(printf '%s' "${APP:-}" | sha256sum | awk '{print $1}')-$(sha256_file version.txt)"

  write_output version-key "$key"
  write_output gpg-cache-key package-gpg-key-v1

  if [[ "${GITHUB_EVENT_NAME:-}" == workflow_dispatch ]]; then
    changed=true
  else
    cache_keys="$(gh cache list --key "$key" --json key --jq '.[].key')"
    if grep -qxF "$key" <<<"$cache_keys"; then
      changed=false
    else
      changed=true
    fi
  fi

  write_output changed "$changed"
}

