TARGET_FAMILY_REGEX='^alma-[0-9]+$'
TARGET_ARCHES='x86_64 aarch64 ppc64le s390x i686 armv7hnl'
TARGET_LABEL_STRIP_PREFIX='alma-'
TARGET_LABEL_TEMPLATE='AlmaLinux {suffix}'
TARGET_LABEL_CASE='raw'
TARGET_INSTALL_TOOL='dnf'
TARGET_CONTAINER_IMAGE='fedora:latest'
TARGET_CONTAINER_BUILD_CMD='dnf -y install bash createrepo_c curl diffutils findutils git gnupg2 mock mock-core-configs patch rpm-build rpm-sign rpmdevtools sed tar util-linux which && dnf clean all'
