TARGET_FAMILY_REGEX='^openmandriva-(cooker|rolling|[0-9]+(\.[0-9]+)?)$'
TARGET_ARCHES='x86_64 aarch64 ppc64le s390x i686 armv7hnl'
TARGET_LABEL_STRIP_PREFIX='openmandriva-'
TARGET_LABEL_TEMPLATE='OpenMandriva {suffix}'
TARGET_LABEL_CASE='title'
TARGET_INSTALL_TOOL='dnf'
TARGET_CONTAINER_IMAGE='fedora:latest'
TARGET_CONTAINER_BUILD_CMD='dnf -y install bash createrepo_c curl diffutils findutils git gnupg2 mock mock-core-configs patch rpm-build rpm-sign rpmdevtools sed tar util-linux which && dnf clean all'
TARGET_RPM_CHROOT_SETUP_CMD='install rpm-build findutils coreutils bash curl'
TARGET_RPM_MOCK_CONFIG_OPTS='--no-bootstrap-chroot'
