TARGET_FAMILY_REGEX='^gnome-rust-(48|49)$'
TARGET_ARCHES='x86_64 aarch64'
TARGET_CONTAINER_IMAGE_TEMPLATE='ghcr.io/andyholmes/flatter/gnome-rust:{suffix}'
TARGET_CONTAINER_IMAGE_STRIP_PREFIX='gnome-rust-'
