TARGET_FAMILY_REGEX='^rust-nightly-(24\.08|25\.08)$'
TARGET_ARCHES='x86_64'
TARGET_CONTAINER_IMAGE_TEMPLATE='ghcr.io/andyholmes/flatter/rust-nightly:{suffix}'
TARGET_CONTAINER_IMAGE_STRIP_PREFIX='rust-nightly-'
