TARGET_FAMILY_REGEX='^workbench1-master$'
TARGET_ARCHES='x86_64 aarch64'
TARGET_CONTAINER_IMAGE_TEMPLATE='ghcr.io/andyholmes/flatter/workbench1:{suffix}'
TARGET_CONTAINER_IMAGE_STRIP_PREFIX='workbench1-'
